---
- name: Create user and skeleton home directory
  user:
    name: "{{ item }}"
    state: present
    password: "{{ password }}"
    shell: /bin/bash
    groups: 
      - admin
      - sudo
    create_home: yes
    skeleton: /etc/skel
  with_items:
    - "{{ users }}"

- name: create ssh folder
  file:
    path: /home/{{ item }}/.ssh
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ users }}"

- name: generate a 2048-bit ssh key for user in .ssh directory
  user:
    name: "{{ item }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048      
    ssh_key_file: /home/{{ item }}/.ssh/{{ item }}_id_rsa
  with_items:
    - "{{ users }}"

- name: install config file on all users
  template:
    src: "config.j2"
    dest: "/home/{{ item }}/.ssh/config"
  with_items:
    - "{{ users }}"
