---
- name: Installing git on gitServer
  package:
      name:
        - git
        - acl
      state: present
 
- name: create git user
  user:
    name: git
    shell: /bin/bash
    home: /home/git
    group: sudo
  

- name: add Keys to git server
  ansible.posix.authorized_key:
    user: git
    state: present
    key: "{{ lookup('file', '{{begin}}{{item}}{{middle}}{{item}}{{end}}') }}"
  with_items:
    - "{{ users }}"

- name: Create Repositories
  command: "{{ 'git init --bare  /home/git/repos/' + item + '.git' }}"
  become_user: git
  args:
    creates: "{{ '/home/git/repos/' + item + '.git/HEAD' }}"
  loop:
    - repo1
    - repo2
